import turtle
turtle.goto(0,0)
turtle.pendown()
turtle.pensize(2)
turtle.pencolor('blue')
turtle.circle(20)
turtle.penup()
turtle.goto(40,0)
turtle.pendown()
turtle.pensize(2)
turtle.pencolor('black')
turtle.circle(20)
turtle.penup()
turtle.goto(80,0)
turtle.pendown()
turtle.pensize(2)
turtle.pencolor('brown')
turtle.circle(20)
turtle.penup()
turtle.goto(20,-20)
turtle.pensize(2)
turtle.pencolor('green')
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.goto(60,-20)
turtle.pensize(2)
turtle.pencolor('brown')
turtle.pendown()
turtle.circle(20)
turtle.penup()


